apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: abc-api
  name: abc-api
spec:
  output:
    to:
      kind: ImageStreamTag
      name: abc-api:latest
      namespace: abc
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/anilabhabaral/build-test.git
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      buildArgs:
        - name: APP_VERSION
          value: tmp
        - name: TEST
          value: dkoci
      dockerfilePath: src/main/docker/Dockerfile.jvm
